ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Prefix "/pimepunkt"

ProxyPass /pimepunkt/ http://127.0.0.1:8088/
ProxyPassReverse /pimepunkt/ http://127.0.0.1:8088/
ProxyPass /pimepunkt http://127.0.0.1:8088/
ProxyPassReverse /pimepunkt http://127.0.0.1:8088/
